CREATE TABLE academic_degree(
                                id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                academic_degree_name varchar unique NOT NULL ,
                                work_limit int not null CHECK ( work_limit > 0 )
);

CREATE TABLE teacher(
                        teacher_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fio varchar NOT NULL ,
                        academic_degree int REFERENCES academic_degree(id) ON DELETE SET NULL ,
                        working_rate double precision NOT NULL check ( working_rate > 0 ),
                        image_file_name varchar,
                        max_work_hours double precision check ( max_work_hours > 0 ),
                        actual_working_hours double precision check ( actual_working_hours >= 0 )
);

CREATE TABLE group_of_students(
                                  group_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  speciality varchar NOT NULL,
                                  year_of_entering int NOT NULL check ( year_of_entering > 2015 ),
                                  number_of_students int NOT NULL CHECK ( number_of_students > 0)
);

CREATE TABLE sub_group_of_student(
                                     sub_group_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     main_group int NOT NULL REFERENCES group_of_students(group_id) ON DELETE CASCADE ,
                                     numberOfStudents int NOT NULL CHECK ( numberOfStudents > 0 )
);

CREATE TABLE education_discipline(
                                     education_discipline_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     education_discipline_name varchar NOT NULL UNIQUE,
                                     duration int NOT NULL CHECK ( duration > 0 ),
                                     recommended_teacher int REFERENCES teacher(teacher_id) ON DELETE SET NULL ,
                                     max_students int check ( max_students > 0 )
);

CREATE TABLE schedule(
                         schedule_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         sub_group_id int NOT NULL REFERENCES sub_group_of_student(sub_group_id) ON DELETE CASCADE ,
                         teacher int REFERENCES teacher(teacher_id) ON DELETE SET NULL ,
                         education_discipline_id int NOT NULL REFERENCES education_discipline(education_discipline_id) ON DELETE CASCADE
);